phpList/updater

index.php
=> unzip function

version.json
=> set autoupdater to 1

index.php
=> Create function that returns the current version of phpList

index.php
=> Fix response from server and check for update

index.php
=>  Recursively delete a directory and all of it's contents

index.php
return unexpected files or continue, return the not writeable file or continue, download or catch e
=> return unexpected files or continue, return not writeable file or continue, download or catch e

index.php
=> Return boolean after checking if there is an available update

index.php
=> Create PDO connection, Set maintenance mode

index.php
=> Clear maintenance mode function

index.php
Todo: Determine how to proceed if an update is already running.
Currently the script is dying, not the prettiest way to handle it.
Deals with #22
=> Add lock to prevent concurent updates

index.php
=> reset opcache

index.php
=> steps + callback logic, delete temp files, etc

index.php
Fix #44 #1 
- Check if the user is authenticated by using session
- Move updater to a new location before temp folder is deleted.
- As the final step move the new updater in place.
=> Check if user is authenticated and update updater

index.php
-Fix download Url
-Fix backup location, 
-fix updating updater itself, 
-redirect to the admin page as the final step, fix #9 
-Retry option if smth fails.
-Other various bug fixes. 
-Add style for disabled next button
=> Fix backup location, fix updating updater itself, redirect to admin etc

index.php
=> Update icons svgs

index.php
=> Update the last icon, change active colour, etc

index.php
as requested from @rudolfburgaj
=> Remove outline if the step is active

index.php
=> Check if the required php modules are missing

README.md
=> Permissions

index.php
=> Improve message

index.php
https://mantis.phplist.org/view.php?id=19742
=> Max screen resolution

index.php
https://mantis.phplist.org/view.php?id=19743
=> Center text between tabs

index.php
- Added "Error: " before error messages including  https://mantis.phplist.org/view.php?id=19623
- fixed CSS indentation
=> Added "Error: " before error messages, fixed css indent

index.php
https://mantis.phplist.org/view.php?id=19848
=> Do not overwrite plugins during update

index.php
- Use table prefix if it is set
- Fix https://mantis.phplist.org/view.php?id=19780
=> Update "maintenance mode" queries to use $table_prefix

index.php
To be merged after https://github.com/phpList/phplist3/pull/506 is merged.
=> Add api.php to the list of entrypoints

index.php
Constant expressions are not supported in older versions than PHP 5.6.
https://www.php.net/manual/en/migration56.new-features.php
=> Don't use constant expressions (to support old PHP versions)

index.php
https://mantis.phplist.org/view.php?id=19627
=> Mantis 19627

index.php
Initially reported here: https://discuss.phplist.org/t/updater-problem-with-non-existent-file/5428/3
@samtuke can you please check the wording?
=> edit error message to avoid confusion
